services:
  api-dev:
    image: ghcr.io/amgadhasan/e-commerce-expert-assistant:main
    volumes:
      - type: bind
        source: /home/azureuser/e-commerce-chatbot/api.log
        target: /app/api.log
    ports:
      - "3000:8000"
    env_file:
      - .env
    depends_on:
      - embedding_service
    profiles: ["dev"]
    networks:
      - app-network
  
  embedding_service:
    environment:
      - MODEL_ID=BAAI/bge-m3
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.6
    ports:
      - "8765:80"
    volumes:
      - ~/models:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge